version: "3" # faire attention a la version 
services: 
  db:  #mettre le nom qu'on veut
    container_name: mysqlshark # nom du container
    image: mysql:5.7 #son image
    ports:
      - "9001:3306"  #localhost, lan docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yoo 
      MYSQL_DATABASE: app_db
      MYSQL_USER: gosman
      MYSQL_PASSWORD: yoo
    volumes: #éphemere, il faut donc la stocker
      - ./dbdata:/var/lib/mysql
  phpmyadmin: 
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: "lucas-sandery"
    links:
      - db
